import { Geist, Geist_Mono } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const open_sans = Open_Sans({
  subsets: ['latin'],
  weight: ['400','700'],
})

export const metadata = {
  title: "Despegamos con",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${open_sans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
